# Docker Compose for jenkins
version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - jenkinsNetwork
    ports:
      - '8085:8080'
      - '50000:50000'
    volumes:
      - './jenkins_data:/var/jenkins_home'
networks:
  jenkinsNetwork:
    name: jenkins

